create database 数据库名 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE `products` (
  `ProductID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(255) DEFAULT NULL,
  `Quantity` int(11) DEFAULT NULL,
  `Price` int(11) DEFAULT NULL,
  PRIMARY KEY (`ProductID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `Tb_ExceptionLogPcAuto` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `LogLevel` VARCHAR(200) DEFAULT NULL,
  `LogMessage` VARCHAR(4000) DEFAULT NULL,
  `LogBusinessTopic` VARCHAR(200) DEFAULT NULL,
  `CreateDatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OtherMessage` LONGTEXT,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
#INSERT INTO Tb_ExceptionLogPcAuto(LogLevel, LogMessage, LogBusinessTopic, OtherMessage)
#  VALUES('LogLevel000', 'LogMessage009', 'LogBusinessTopic009', 'OtherMessage009')

CREATE TABLE `Tb_OperationLogPcAuto` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `OperationLevel` VARCHAR(200) DEFAULT NULL,
  `OperationMessage` VARCHAR(4000) DEFAULT NULL,
  `OperationBusinessTopic` VARCHAR(200) DEFAULT NULL,
  `CreateDatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OtherMessage` LONGTEXT,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
#INSERT INTO Tb_OperationLogPcAuto(OperationLevel, OperationMessage, OperationBusinessTopic, OtherMessage)
#  VALUES('LogLevel000', 'LogMessage009', 'LogBusinessTopic009', 'OtherMessage009')

CREATE TABLE `Tb_HisCar` (
  `OperationId` int(11) NOT NULL,
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `TaskId` VARCHAR(200) DEFAULT NULL,
  `TaskGroupId` VARCHAR(200) DEFAULT NULL,
  `CompatibleTaskId` VARCHAR(200) DEFAULT NULL,
  `RuntimeRefUrl` VARCHAR(2000) DEFAULT NULL,
  `RuntimeHttpMocker` VARCHAR(8000) DEFAULT NULL,
  `RuntimeFirstPageUrl` VARCHAR(2000) DEFAULT NULL,
  `PcAutoUserId` VARCHAR(100) DEFAULT NULL,
  `IsMultiPage` int(1) DEFAULT 0,
  `CrawledDataUrl` VARCHAR(2000) DEFAULT NULL,
  `CrawledDataContent` LONGTEXT DEFAULT NULL,
  `CrawledDataTime` VARCHAR(200) DEFAULT NULL,
  `CreateDatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OtherMessage` LONGTEXT,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
#SELECT * FROM TB_HISCAR


CREATE TABLE `Tb_HisCarQuestion` (
  `OperationId` int(11) NOT NULL,
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `TaskId` VARCHAR(200) DEFAULT NULL,
  `TaskGroupId` VARCHAR(200) DEFAULT NULL,
  `CompatibleTaskId` VARCHAR(200) DEFAULT NULL,
  `RuntimeRefUrl` VARCHAR(2000) DEFAULT NULL,
  `RuntimeHttpMocker` VARCHAR(8000) DEFAULT NULL,
  `RuntimeFirstPageUrl` VARCHAR(2000) DEFAULT NULL,
  `PcAutoUserId` VARCHAR(100) DEFAULT NULL,
  `IsMultiPage` int(1) DEFAULT 0,
  `CrawledDataUrl` VARCHAR(2000) DEFAULT NULL,
  `CrawledDataContent` LONGTEXT DEFAULT NULL,
  `CrawledDataTime` VARCHAR(200) DEFAULT NULL,
  `CreateDatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OtherMessage` LONGTEXT,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
SELECT * FROM Tb_HisCarQuestion

CREATE TABLE `Tb_HisCarAnswer` (
  `OperationId` int(11) NOT NULL,
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `TaskId` VARCHAR(200) DEFAULT NULL,
  `TaskGroupId` VARCHAR(200) DEFAULT NULL,
  `CompatibleTaskId` VARCHAR(200) DEFAULT NULL,
  `RuntimeRefUrl` VARCHAR(2000) DEFAULT NULL,
  `RuntimeHttpMocker` VARCHAR(8000) DEFAULT NULL,
  `RuntimeFirstPageUrl` VARCHAR(2000) DEFAULT NULL,
  `PcAutoUserId` VARCHAR(100) DEFAULT NULL,
  `IsMultiPage` int(1) DEFAULT 0,
  `CrawledDataUrl` VARCHAR(2000) DEFAULT NULL,
  `CrawledDataContent` LONGTEXT DEFAULT NULL,
  `CrawledDataTime` VARCHAR(200) DEFAULT NULL,
  `CreateDatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OtherMessage` LONGTEXT,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `Tb_HisCommentPost` (
  `OperationId` int(11) NOT NULL,
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `TaskId` VARCHAR(200) DEFAULT NULL,
  `TaskGroupId` VARCHAR(200) DEFAULT NULL,
  `CompatibleTaskId` VARCHAR(200) DEFAULT NULL,
  `RuntimeRefUrl` VARCHAR(2000) DEFAULT NULL,
  `RuntimeHttpMocker` VARCHAR(8000) DEFAULT NULL,
  `RuntimeFirstPageUrl` VARCHAR(2000) DEFAULT NULL,
  `PcAutoUserId` VARCHAR(100) DEFAULT NULL,
  `IsMultiPage` int(1) DEFAULT 0,
  `CrawledDataUrl` VARCHAR(2000) DEFAULT NULL,
  `CrawledDataContent` LONGTEXT DEFAULT NULL,
  `CrawledDataTime` VARCHAR(200) DEFAULT NULL,
  `CreateDatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OtherMessage` LONGTEXT,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
SELECT * FROM Tb_HisCommentPost

CREATE TABLE `Tb_HisCommentReply` (
  `OperationId` int(11) NOT NULL,
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `TaskId` VARCHAR(200) DEFAULT NULL,
  `TaskGroupId` VARCHAR(200) DEFAULT NULL,
  `CompatibleTaskId` VARCHAR(200) DEFAULT NULL,
  `RuntimeRefUrl` VARCHAR(2000) DEFAULT NULL,
  `RuntimeHttpMocker` VARCHAR(8000) DEFAULT NULL,
  `RuntimeFirstPageUrl` VARCHAR(2000) DEFAULT NULL,
  `PcAutoUserId` VARCHAR(100) DEFAULT NULL,
  `IsMultiPage` int(1) DEFAULT 0,
  `CrawledDataUrl` VARCHAR(2000) DEFAULT NULL,
  `CrawledDataContent` LONGTEXT DEFAULT NULL,
  `CrawledDataTime` VARCHAR(200) DEFAULT NULL,
  `CreateDatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OtherMessage` LONGTEXT,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
SELECT * FROM Tb_HisCommentReply

CREATE TABLE `Tb_HisComment` (
  `OperationId` int(11) NOT NULL,
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `TaskId` VARCHAR(200) DEFAULT NULL,
  `TaskGroupId` VARCHAR(200) DEFAULT NULL,
  `CompatibleTaskId` VARCHAR(200) DEFAULT NULL,
  `RuntimeRefUrl` VARCHAR(2000) DEFAULT NULL,
  `RuntimeHttpMocker` VARCHAR(8000) DEFAULT NULL,
  `RuntimeFirstPageUrl` VARCHAR(2000) DEFAULT NULL,
  `PcAutoUserId` VARCHAR(100) DEFAULT NULL,
  `IsMultiPage` int(1) DEFAULT 0,
  `CrawledDataUrl` VARCHAR(2000) DEFAULT NULL,
  `CrawledDataContent` LONGTEXT DEFAULT NULL,
  `CrawledDataTime` VARCHAR(200) DEFAULT NULL,
  `CreateDatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OtherMessage` LONGTEXT,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
SELECT * FROM Tb_HisComment


CREATE TABLE `Tb_HisHomeFocusNumber` (
  `OperationId` int(11) NOT NULL,
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `TaskId` VARCHAR(200) DEFAULT NULL,
  `TaskGroupId` VARCHAR(200) DEFAULT NULL,
  `CompatibleTaskId` VARCHAR(200) DEFAULT NULL,
  `RuntimeRefUrl` VARCHAR(2000) DEFAULT NULL,
  `RuntimeHttpMocker` VARCHAR(8000) DEFAULT NULL,
  `RuntimeFirstPageUrl` VARCHAR(2000) DEFAULT NULL,
  `PcAutoUserId` VARCHAR(100) DEFAULT NULL,
  `IsMultiPage` int(1) DEFAULT 0,
  `CrawledDataUrl` VARCHAR(2000) DEFAULT NULL,
  `CrawledDataContent` LONGTEXT DEFAULT NULL,
  `CrawledDataTime` VARCHAR(200) DEFAULT NULL,
  `CreateDatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OtherMessage` LONGTEXT,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
SELECT * FROM Tb_HisHomeFocusNumber

CREATE TABLE `Tb_HisHomeFansNumber` (
  `OperationId` int(11) NOT NULL,
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `TaskId` VARCHAR(200) DEFAULT NULL,
  `TaskGroupId` VARCHAR(200) DEFAULT NULL,
  `CompatibleTaskId` VARCHAR(200) DEFAULT NULL,
  `RuntimeRefUrl` VARCHAR(2000) DEFAULT NULL,
  `RuntimeHttpMocker` VARCHAR(8000) DEFAULT NULL,
  `RuntimeFirstPageUrl` VARCHAR(2000) DEFAULT NULL,
  `PcAutoUserId` VARCHAR(100) DEFAULT NULL,
  `IsMultiPage` int(1) DEFAULT 0,
  `CrawledDataUrl` VARCHAR(2000) DEFAULT NULL,
  `CrawledDataContent` LONGTEXT DEFAULT NULL,
  `CrawledDataTime` VARCHAR(200) DEFAULT NULL,
  `CreateDatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OtherMessage` LONGTEXT,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
SELECT * FROM Tb_HisHomeFansNumber

CREATE TABLE `Tb_HisHomeLoveCars` (
  `OperationId` int(11) NOT NULL,
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `TaskId` VARCHAR(200) DEFAULT NULL,
  `TaskGroupId` VARCHAR(200) DEFAULT NULL,
  `CompatibleTaskId` VARCHAR(200) DEFAULT NULL,
  `RuntimeRefUrl` VARCHAR(2000) DEFAULT NULL,
  `RuntimeHttpMocker` VARCHAR(8000) DEFAULT NULL,
  `RuntimeFirstPageUrl` VARCHAR(2000) DEFAULT NULL,
  `PcAutoUserId` VARCHAR(100) DEFAULT NULL,
  `IsMultiPage` int(1) DEFAULT 0,
  `CrawledDataUrl` VARCHAR(2000) DEFAULT NULL,
  `CrawledDataContent` LONGTEXT DEFAULT NULL,
  `CrawledDataTime` VARCHAR(200) DEFAULT NULL,
  `CreateDatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OtherMessage` LONGTEXT,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
SELECT * FROM Tb_HisHomeLoveCars

CREATE TABLE `Tb_HisHomeUserSetting` (
  `OperationId` int(11) NOT NULL,
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `TaskId` VARCHAR(200) DEFAULT NULL,
  `TaskGroupId` VARCHAR(200) DEFAULT NULL,
  `CompatibleTaskId` VARCHAR(200) DEFAULT NULL,
  `RuntimeRefUrl` VARCHAR(2000) DEFAULT NULL,
  `RuntimeHttpMocker` VARCHAR(8000) DEFAULT NULL,
  `RuntimeFirstPageUrl` VARCHAR(2000) DEFAULT NULL,
  `PcAutoUserId` VARCHAR(100) DEFAULT NULL,
  `IsMultiPage` int(1) DEFAULT 0,
  `CrawledDataUrl` VARCHAR(2000) DEFAULT NULL,
  `CrawledDataContent` LONGTEXT DEFAULT NULL,
  `CrawledDataTime` VARCHAR(200) DEFAULT NULL,
  `CreateDatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OtherMessage` LONGTEXT,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
SELECT * FROM Tb_HisHomeUserSetting

CREATE TABLE `Tb_HisHomeOfficalClub` (
  `OperationId` int(11) NOT NULL,
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `TaskId` VARCHAR(200) DEFAULT NULL,
  `TaskGroupId` VARCHAR(200) DEFAULT NULL,
  `CompatibleTaskId` VARCHAR(200) DEFAULT NULL,
  `RuntimeRefUrl` VARCHAR(2000) DEFAULT NULL,
  `RuntimeHttpMocker` VARCHAR(8000) DEFAULT NULL,
  `RuntimeFirstPageUrl` VARCHAR(2000) DEFAULT NULL,
  `PcAutoUserId` VARCHAR(100) DEFAULT NULL,
  `IsMultiPage` int(1) DEFAULT 0,
  `CrawledDataUrl` VARCHAR(2000) DEFAULT NULL,
  `CrawledDataContent` LONGTEXT DEFAULT NULL,
  `CrawledDataTime` VARCHAR(200) DEFAULT NULL,
  `CreateDatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OtherMessage` LONGTEXT,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
SELECT * FROM Tb_HisHomeOfficalClub

CREATE TABLE `Tb_HisHomeNormalClob` (
  `OperationId` int(11) NOT NULL,
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `TaskId` VARCHAR(200) DEFAULT NULL,
  `TaskGroupId` VARCHAR(200) DEFAULT NULL,
  `CompatibleTaskId` VARCHAR(200) DEFAULT NULL,
  `RuntimeRefUrl` VARCHAR(2000) DEFAULT NULL,
  `RuntimeHttpMocker` VARCHAR(8000) DEFAULT NULL,
  `RuntimeFirstPageUrl` VARCHAR(2000) DEFAULT NULL,
  `PcAutoUserId` VARCHAR(100) DEFAULT NULL,
  `IsMultiPage` int(1) DEFAULT 0,
  `CrawledDataUrl` VARCHAR(2000) DEFAULT NULL,
  `CrawledDataContent` LONGTEXT DEFAULT NULL,
  `CrawledDataTime` VARCHAR(200) DEFAULT NULL,
  `CreateDatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OtherMessage` LONGTEXT,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
SELECT * FROM Tb_HisHomeNormalClob

CREATE TABLE `Tb_HisHome` (
  `OperationId` int(11) NOT NULL,
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `TaskId` VARCHAR(200) DEFAULT NULL,
  `TaskGroupId` VARCHAR(200) DEFAULT NULL,
  `CompatibleTaskId` VARCHAR(200) DEFAULT NULL,
  `RuntimeRefUrl` VARCHAR(2000) DEFAULT NULL,
  `RuntimeHttpMocker` VARCHAR(8000) DEFAULT NULL,
  `RuntimeFirstPageUrl` VARCHAR(2000) DEFAULT NULL,
  `PcAutoUserId` VARCHAR(100) DEFAULT NULL,
  `IsMultiPage` int(1) DEFAULT 0,
  `CrawledDataUrl` VARCHAR(2000) DEFAULT NULL,
  `CrawledDataContent` LONGTEXT DEFAULT NULL,
  `CrawledDataTime` VARCHAR(200) DEFAULT NULL,
  `CreateDatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `OtherMessage` LONGTEXT,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
SELECT * FROM Tb_HisHome